# Generated by Django 4.2.3 on 2023-07-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_post_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("name", models.CharField(max_length=200)),
                ("photo", models.ImageField(upload_to="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
